[package]
name = "tcp_chat"
version = "0.1.0"
edition = "2021"


[dependencies]
tokio = { version = "1.16.1", features = ["full"] }
env_logger = "0.9.0"
libp2p = { version = "0.41", features = ["tcp-tokio"] }
futures = "0.3.21"
async-std = "1.10.0"

